Checking plan: /Users/spinute/Dropbox/program/parse2zinc/tmp/answer
Plan executed successfully - checking goal
Plan valid
Final value: 26 

Successful plans:
Value: 26
 /Users/spinute/Dropbox/program/parse2zinc/tmp/answer 26 

