Checking plan: /Users/spinute/Dropbox/program/parse2zinc/tmp/answer
Plan executed successfully - checking goal
Plan valid
Final value: 3 

Successful plans:
Value: 3
 /Users/spinute/Dropbox/program/parse2zinc/tmp/answer 3 

