Checking plan: /Users/spinute/Dropbox/program/parse2zinc/tmp/answer
Plan executed successfully - checking goal
Plan valid
Final value: 4 

Successful plans:
Value: 4
 /Users/spinute/Dropbox/program/parse2zinc/tmp/answer 4 

