#!/bin/bash


ZINC_HOME=~/Dropbox/program/parse2zinc
ANS=$ZINC_HOME/tmp/answer
MAIN=$ZINC_HOME/bin/opti_main
BENCH=$ZINC_HOME/benchmarks

FD_HOME=~/1123fast
TRANSRATE=$FD_HOME/src/translate/translate.py 
VALIDATE=$FD_HOME/src/VAL/validate

# !!!!
#change these variable for change domain and problem
SMALLDOMAINS=(gripper logistics98 blocks grid mprime)
DOMAINS=(gripper    logistics98 blocks              grid           mprime      mystery     depot       driverlog   zenotravel  airport              psr-small             pipesworld-tankage      tpp         storage     elevators-sat08-strips elevators-opt08-strips assembly    trucks      psr-middle             psr-large              pipeworld-notankage movie       miconic     satellite       rovers      freecell    pathways        trucks-strips   parcprinter-08-strips)
PROBS=(domain.pddl  domain.pddl domain.pddl         domain.pddl    domain.pddl domain.pddl domain.pddl domain.pddl domain.pddl p01-airport1-p1.pddl p01-domain.pddl       domain.pddl             domain.pddl domain.pddl p01-domain.pddl        p01-domain.pddl        domain.pddl domain.pddl domain.pddl            domain.pddl            domain.pddl         domain.pddl domain.pddl domain.pddl     domain.pddl domain.pddl domain_p01.pddl domain_p01.pddl p01-domain.pddl)
PROBXS=(prob01.pddl prob01.pddl probBLOCKS-4-0.pddl prob01.pddl    prob01.pddl prob01.pddl pfile1      pfile1      pfile1      p01-domain.pddl      p01-s2-n1-l2-f50.pddl p01-net1-b6-g2-t50.pddl p01.pddl    p01.pddl    p01.pddl               p01.pddl               prob01.pddl p01.pddl    p01-s17-n2-l2-f30.pddl p01-s29-n2-l5-f30.pddl p01-net1-b6-g2.pddl prob01.pddl s1-0.pddl   p01-pfile1.pddl p01.pddl    pfile1      p01.pddl        p01.pddl        p01.pddl)
# airport, openstacks-strips
#openstacks-strips 
#domain_p01.pddl
#p01.pddl          

for ((i=0; i<29; i++)) 
do

THISDOM=${DOMAINS[$i]}
PROB=$BENCH/$THISDOM/${PROBS[$i]}
PROBX=${PROBXS[$i]}

PROBLEM=$BENCH/$THISDOM/$PROBX
RESULT=opti_result
VALIDATE_RESULT=$ZINC_HOME/${RESULT}/validate_${THISDOM}_${PROBX}

$TRANSRATE $PROB $PROBLEM ## --relaxed -> remove negative effect
mv output.sas $ZINC_HOME/tmp

$MAIN $ZINC_HOME/tmp/output.sas

###### VAL
$VALIDATE $PROB $PROBLEM $ANS > $VALIDATE_RESULT

TESTLOG=$ZINC_HOME/$RESULT/testlog
echo $VALIDATE_RESULT | $ZINC_HOME/bin/check_valid >> $TESTLOG
echo "$THISDOM: $PROBX" >> $TESTLOG

###### compare with fastdownward result
$FD_HOME/src/preprocess/preprocess < $ZINC_HOME/tmp/output.sas
$FD_HOME/src/fast-downward.py output --search "astar(lmcut())" 

if [ -f $ZINC_HOME/objval ]; then
	mv $ZINC_HOME/sas_plan $ZINC_HOME/output $ZINC_HOME/objval $ZINC_HOME/tmp
	$ZINC_HOME/script/get_planValue $THISDOM $PROBX >> $TESTLOG
fi

date >> $TESTLOG
echo "" >> $TESTLOG

###### 実験はmasterからやろう
git commit -am 'autocommit for test'

if [ -f $ZINC_HOME/sas_plan.* ]; then
	mv $ZINC_HOME/sas_plan.* $ZINC_HOME/tmp
fi

done;
exit 0