#!/bin/bash

ZINC=~/Dropbox/program/parse2zinc
ANS=$ZINC/tmp/answer
GENERATE=$ZINC/bin/opti_main
BENCH=$ZINC/benchmarks

FD_HOME=~/1123fast
TRANSRATE=$FD_HOME/src/translate/translate.py 
VALIDATE=$FD_HOME/src/VAL/validate

# !!!!
#change these variable for change domain and problem

THISDOM=airport
THISPROB=p01-airport-p1.pddl
DOMAIN=$BENCH/$THISDOM/p01-domain.pddl
# !!!!

###### do
PROBLEM=$BENCH/$THISDOM/$THISPROB
RESULT=opti_result
VALIDATE_RESULT=$ZINC/${RESULT}/validate_${THISDOM}_${THISPROB}

$TRANSRATE $DOMAIN $PROBLEM ## --relaxed -> remove negative effect
mv output.sas $ZINC/tmp

$GENERATE $ZINC/tmp/output.sas

###### VAL
$VALIDATE $DOMAIN $PROBLEM $ANS > $VALIDATE_RESULT

TESTLOG=$ZINC/$RESULT/testlog
echo $VALIDATE_RESULT | $ZINC/bin/check_valid >> $TESTLOG
echo "$THISDOM: $THISPROB" >> $TESTLOG

###### compare with fastdownward result
$FD_HOME/src/preprocess/preprocess < $ZINC/tmp/output.sas
$FD_HOME/src/fast-downward.py output --search "astar(lmcut())"
# $FD_HOME/src/fast-downward.py --alias seq-sat-lama-2011 output

if [ -f $ZINC/objval ]; then
	mv $ZINC/sas_plan $ZINC/output $ZINC/objval $ZINC/tmp
	$ZINC/script/get_planValue $THISDOM $THISPROB >> $TESTLOG
fi

date >> $TESTLOG
echo "" >> $TESTLOG

###### 実験はmasterからやろう
git commit -am 'autocommit for test'

if [ -f $ZINC/sas_plan.* ]; then
	mv $ZINC/sas_plan.* $ZINC/tmp
fi

exit 0