#!/bin/bash

ZINC=~/Dropbox/program/parse2zinc
ANS=$ZINC/tmp/ans_plan
GENERATE=$ZINC/bin/sas_generator
BENCH=$ZINC/benchmarks

FD=~/1123fast
TRANSRATE=$FD/src/translate/translate.py 
VALIDATE=$FD/src/VAL/validate

##############
#change these variable for change domain and problem
THISDOM=gripper
THISTEST=prob01.pddl
DOMAIN=$BENCH/$THISDOM/domain.pddl
##############

PROBLEM=$BENCH/$THISDOM/$THISTEST
VALIDATE_RESULT=$ZINC/result/validate_${THISDOM}_${THISTEST}


$TRANSRATE $DOMAIN $PROBLEM
mv output.sas $ZINC/tmp

$GENERATE $ZINC/tmp/output.sas

$VALIDATE $DOMAIN $PROBLEM $ANS > $VALIDATE_RESULT

echo $VALIDATE_RESULT | $ZINC/bin/check_valid >> $ZINC/result/testlog
echo "$THISDOM: $THISTEST" >> $ZINC/result/testlog

$FD/src/preprocess/preprocess < $ZINC/tmp/output.sas
$FD/src/fast-downward.py --alias seq-sat-lama-2011 output

exit 0