#include "/Library/gurobi563/mac64/include/gurobi_c++.h"

using namespace std;

#include <chrono>
#include "sas_parser.cc"
#include "zinc_generator_global.cc"
// #include "opti_pgraph.cc"

int main(int argc, char const *argv[])
{
	// check execution format: this program require sas format for input file
	// this file should be generated by pddl tlanslator of fastdownward
	if (argc <= 2)
	{
		cout << "usage: opti_main <file>.sas level" << endl;
		return -1;
	}

	auto startTime = std::chrono::system_clock::now();
	Problem *problem_ptr = parse2gurobi(argv[1]);
	// int t = create_planningGraph(*problem_ptr);
	// cout << t << endl;
	// exit(1);
	auto endTime = std::chrono::system_clock::now();
	auto timeSpan = endTime - startTime;
	std::cerr << "time(parse):" << std::chrono::duration_cast<std::chrono::milliseconds>(timeSpan).count() << "[ms]" << std::endl;
		
	int level = atoi(argv[2]);
	startTime = std::chrono::system_clock::now();
	zinc_gen(level, *problem_ptr);
	// for (int i = 1; i < 17 ; ++i)
	// {
	// 	cerr << "level: " << i << endl;
	// 	if (zinc_gen(i, *problem_ptr))
	// 		break;
	// }
	endTime = std::chrono::system_clock::now();
	timeSpan = endTime - startTime;
	std::cerr << "time(zinc_gen):" << std::chrono::duration_cast<std::chrono::milliseconds>(timeSpan).count() << "[ms]" << std::endl;

	return 0;
}